name: Main Workflow

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Website 
      uses: actions/setup-node@v1
    - name: npm install, build, generate
      run: |
        npm install
        npm run build
        npm run generate
