name: Main Workflow

on:
  push:
    branches:
    - master
    - release/*
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Website 
      uses: actions/setup-node@v1
    - name: npm install, build
      run: |
        npm install
        npm run build
